# 18/04 - Pair Programming Pandas 1 - Tatiana & Lara

In [2]:
import pandas as pd
import numpy as np
import random 

¿Qué diferencia hay entre una Serie y un Dataframe?

Una serie es una estructura de datos de una dimensión, un dataframe de dos dimensiones (filas y columnas).

# 1. SERIES

Crea dos listas:
Una que se llame "valores" que tenga 7 números aleatorios.
Otra que se llame "indices" que tenga 7 strings que se llamen como los dias de la semana.

In [3]:
valores = [random.randint(0,7) for x in range(7)] 
indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]
print(valores)
print(indices)

[7, 6, 6, 1, 0, 0, 5]
['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']


A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [4]:
serie = pd.Series(valores, index = indices)
print(serie)

lunes        7
martes       6
miercoles    6
jueves       1
viernes      0
sabado       0
domingo      5
dtype: int64


A partir de las dos listas anteriores crea un diccionario usando un for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. 

In [5]:
dicc = {} 

for indice, valor in zip(indices, valores):
    dicc[indice] = valor
      
print(dicc)


{'lunes': 7, 'martes': 6, 'miercoles': 6, 'jueves': 1, 'viernes': 0, 'sabado': 0, 'domingo': 5}




Crea una Serie con el diccionario creado en el punto anterior.
¿Qué forma tiene esta última Serie?
¿Qué tipo de datos tiene?
¿Qué tamaño tiene?
¿Cuáles son los índices de la Serie?
¿Y los values?


In [6]:
serie_dicc = pd.Series(dicc)
print(serie_dicc)

print("1. La serie tiene la siguiente forma:", serie_dicc.shape)
print("2. La serie tiene este tipo de datos:",serie_dicc.dtype)
print("3. La serie tiene tamaño:", serie_dicc.size)


print("Los índices de la serie son:", serie_dicc.index)
print("Los valores de la serie son:", serie_dicc.values)

lunes        7
martes       6
miercoles    6
jueves       1
viernes      0
sabado       0
domingo      5
dtype: int64
1. La serie tiene la siguiente forma: (7,)
2. La serie tiene este tipo de datos: int64
3. La serie tiene tamaño: 7
Los índices de la serie son: Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')
Los valores de la serie son: [7 6 6 1 0 0 5]


Extraed el valor para el índice "lunes"
Extraed el valor para el índice "lunes", "martes" y "miércoles"
Extraed el valor para el índice "lunes" y "domingo"

In [7]:
valor_lunes = serie_dicc["lunes"]
print("1. El valor del índice 'lunes' es:", valor_lunes,"\n",)


valor_lmx = serie_dicc[[0, 1, 2]] #0:3
print("2. El valor de los índices 'lunes', 'martes', 'miércoles' es:","\n", valor_lmx,"\n",)


valor_ld = serie_dicc[[0, -1]]
print("3. El valor de los índices 'lunes' y 'domingo' es:","\n", valor_ld)

1. El valor del índice 'lunes' es: 7 

2. El valor de los índices 'lunes', 'martes', 'miércoles' es: 
 lunes        7
martes       6
miercoles    6
dtype: int64 

3. El valor de los índices 'lunes' y 'domingo' es: 
 lunes      7
domingo    5
dtype: int64


# 2. Dataframes


Cread un array de dos dimensiones con 4 filas y 3 columnas.


In [8]:
array = np.random.randint(0,100, (4,3))
print(array)
print("Las dimensiones del array son:", array.ndim) #verificamos que tiene dos dimensiones

[[77 87 24]
 [12  2 31]
 [83  6 16]
 [51 16 83]]
Las dimensiones del array son: 2


Convertid el array en un dataframe donde las columnas se llamen "España", "Francia" e "Italia".

In [9]:
dataframe = pd.DataFrame(array, columns = ["España", "Francia", "Italia"])
dataframe

España  Francia  Italia
0      77       87      24
1      12        2      31
2      83        6      16
3      51       16      83

Descargad el archivo "medallas" y cargad el dataframe con la siguiente línea de código:

In [10]:
df = pd.read_csv("1_pandas_medallas.csv", index_col=["País"])
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

Usando el loc extraed todas las columnas de la fila CHINA

In [11]:
china = df.loc["China", :]
china

Unnamed: 0       1
Oro           1473
Plata          994
Bronce         720
Name: China, dtype: int64

Usando el loc extraed todas las columnas de China e Irán.

In [12]:
china_Iran = df.loc[("China", "Irán"),:]
china_Iran

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

Usando el locextraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [13]:
medallas_OPB= df.loc[("China", "Irán"),("Oro", "Plata", "Bronce")]
medallas_OPB

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

Usando el iloc extraed la información de la India. Devolved todas las columnas

In [14]:
india = df.iloc[5,:]
india

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [15]:
impares = df.iloc[1::2]
impares

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce"

In [16]:
o_p_b = impares.iloc[:, -3:]
o_p_b

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

Contestad a las siguientes preguntas:
¿Qué país consiguió más de 200 medallas de oro?
¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [23]:
#Medallas de oro
oro2 = df.loc[(df.Oro > 200)]
print("Los siguientes países consiguieron más de 200 medallas de oro:", "\n", oro2)

#Medallas de oro y plata
oroplata= df.loc[(df.Oro > 200) & (df.Plata > 1000),
    ["Oro", "Plata"]]

print("Los siguientes países consiguieron más de 200 medallas de oro y más de 1000 de plata:", "\n", oroplata)

#Medallas de oro o bronce
orobronce = df.loc[(df.Oro > 200) | (df.Bronce > 700),
    ["Oro", "Bronce"]]

print("Los siguientes países consiguieron más de 200 medallas de oro o más de 700 de bronce:", "\n", oroplata)


Los siguientes países consiguieron más de 200 medallas de oro: 
                 Oro  Plata  Bronce  Total
País                                     
China          1473    994     720   3187
Japón          1032   1037     985   3054
Corea del Sur   745    663     827   2235
Los siguientes países consiguieron más de 200 medallas de oro y más de 1000 de plata: 
         Oro  Plata
País              
Japón  1032   1037
Los siguientes países consiguieron más de 200 medallas de oro o más de 700 de bronce: 
         Oro  Plata
País              
Japón  1032   1037


Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.

In [19]:
df.drop("Unnamed: 0", inplace=True, axis=1)


Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [20]:
df["Total"] = (df["Oro"]+ df["Plata"] + df["Bronce"])
df.head()

Oro  Plata  Bronce  Total
País                                     
China          1473    994     720   3187
Japón          1032   1037     985   3054
Corea del Sur   745    663     827   2235
Irán            179    181     197    557
Kazajistán      155    158     224    537