# 19/04 - Pair Programming Numpy 1 - Tatiana & Lara

# Ejercicio 1 

Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
El valor de la primera fila y la segunda columna.
Los valores de la segunda fila y las dos primeras columnas.
Extraed las filas pares (incluyendo la 0) y todas las columnas.
Extraed los valores que sean mayores que 0.5.
Extraed los valores menores que 0.2 o mayores que 0.5

In [1]:
import numpy as np
array_bidimensional= np.random.rand(5,3)
array_bidimensional

print("Esta es la fila 1, columna 2: ", array_bidimensional[0,1])
print("\n")
print("Esta es la segunda fila y 2 primeras columnas: ", array_bidimensional[1,:2])
print("\n")
print("Estas son las filas pares y todas las columnas. ", array_bidimensional[::2,:])
print("\n")
print("Estos son los valores mayores que 0.5.", array_bidimensional[array_bidimensional>0.5])
print("\n")
print("Estos son los valores menores que 0.2 o mayores que 0.5", array_bidimensional [(array_bidimensional<0.2)|(array_bidimensional>0.5)])

Esta es la fila 1, columna 2:  0.6709561385368809


Esta es la segunda fila y 2 primeras columnas:  [0.026569   0.81370158]


Estas son las filas pares y todas las columnas.  [[0.53525146 0.67095614 0.73722487]
 [0.11706303 0.55146833 0.97377934]
 [0.9612193  0.43957208 0.27967176]]


Estos son los valores mayores que 0.5. [0.53525146 0.67095614 0.73722487 0.81370158 0.55146833 0.97377934
 0.9612193 ]


Estos son los valores menores que 0.2 o mayores que 0.5 [0.53525146 0.67095614 0.73722487 0.026569   0.81370158 0.1988499
 0.11706303 0.55146833 0.97377934 0.17012656 0.07499542 0.9612193 ]


# Ejercicio 2 Cread dos array de tres dimensiones:
 El primero de 2 matrices, 5 filas y 3 columnas.
 El segundo de 3 matrices, 2 filas y 5 columnas
Haced un análisis exploratorio de los array creados

In [2]:
array_1= np.random.randint(0,100, (2,5,3))
array_2= np.random.randint(0,100, (3,2,5))

#FUNCIÓN

def propiedades (array):
    a = ("La forma es:", array.shape)
    b = ("El tamaño es:", array.size)
    c = ("El número de dimensiones es:", array.ndim) 
    d = ("El tipo de datos es:", array.dtype)
    
    print(a, "\n", b, "\n", c, "\n", d)
print("Análisis exploratorio Primer Array")
propiedades(array_1)
print("\n")
print("Análisis exploratorio Segundo Array")
propiedades(array_2)

Análisis exploratorio Primer Array
('La forma es:', (2, 5, 3)) 
 ('El tamaño es:', 30) 
 ('El número de dimensiones es:', 3) 
 ('El tipo de datos es:', dtype('int64'))


Análisis exploratorio Segundo Array
('La forma es:', (3, 2, 5)) 
 ('El tamaño es:', 30) 
 ('El número de dimensiones es:', 3) 
 ('El tipo de datos es:', dtype('int64'))


In [5]:
#Sumad los dos arrays. ¿Podéis? ¿Por qué?
#Suma= array_1+ array_2
#No se pueden sumar estos dos arrays puesto que tienen formas distintas.

Utiliza las funciones .reshape().transpose() para cambiar la forma de los array y hacer operaciones entre ellos

In [3]:
#transformar con transpose() para poder sumar
array_2_transpuesto= np.transpose(array_2,(1,2,0))
array_2_transpuesto

suma_a= array_2_transpuesto + array_1
suma_a

array([[[ 66,  99,  79],
        [146,  83, 113],
        [134, 104,  49],
        [ 64,  90,  60],
        [170, 173, 103]],

       [[ 23,  58,  96],
        [ 87, 103, 125],
        [137,  92,  97],
        [ 17, 102, 129],
        [ 68, 158, 148]]])

In [4]:
#transformar con reshape() para poder sumar
array_2_reshaped= array_2.reshape((2,5,3))
array_2_reshaped

sumar_b= array_1 + array_2_reshaped
sumar_b

array([[[ 66, 145, 110],
        [110,  84,  48],
        [100, 196,  39],
        [ 52,  99,  77],
        [100,  86, 187]],

       [[ 32, 113, 119],
        [128,  96,  89],
        [116,  42,  63],
        [ 21,  73, 155],
        [148, 131, 148]]])