# 18/04 - Pair Programming Numpy 1 - Arrays

In [1]:
import numpy as np

# Ejercicio 1 
Crear 3 arrays. 1) dos dimensiones, 2 filas y 3 col; 2) 3 dim, 2 matrices,3 filas, 5 col. *) 

In [2]:
#Array 1

lista1 = [1, 2, 3, 4, 5]
array_1 =np.array(lista1)
array_1

array([1, 2, 3, 4, 5])

In [3]:
#Array 2 (dos dimensiones, 2 filas, 3 col)

array_2 = np.random.randint (1, 10, (2, 3))
array_2

array([[5, 7, 4],
       [5, 7, 1]])

In [4]:
#Array 3 (2 matrices, 3 filas, 5 col)

array_3 = np.random.rand(2, 3, 5)
array_3

array([[[0.67698729, 0.4086536 , 0.51946063, 0.1261828 , 0.61945935],
        [0.84156824, 0.27027616, 0.46332469, 0.14066922, 0.27939389],
        [0.05017301, 0.64934028, 0.62372353, 0.60436462, 0.28478586]],

       [[0.75207932, 0.01571143, 0.97250728, 0.85581733, 0.37191432],
        [0.04873334, 0.62474225, 0.12604995, 0.14386295, 0.89292197],
        [0.43027618, 0.19337617, 0.26019325, 0.08053639, 0.63155274]]])

# Ejercicio 2 
Función que muestre las propiedades de un array

In [17]:
#FUNCIÓN

def propiedades (array):
    a = "La forma es: ", array.shape
    b = "El tamaño es:", array.size
    c = "El número de dimensiones es:", array.ndim 
    d = "El tipo de datos es:", array.dtype
    
    print( a, "\n", b, "\n", c, "\n", d)



In [18]:
propiedades(array_1)
#propiedades(array_2)
#propiedades(array_3)

('La forma es: ', (5,)) 
 ('El tamaño es:', 5) 
 ('El número de dimensiones es:', 1) 
 ('El tipo de datos es:', dtype('int64'))


# Ejercicio 3 
Crear matriz de identidad

In [7]:
#2 dimensiones, 3 filas y 3 columnas

matriz_ident = np.identity(3)
matriz_ident



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Ejercicio 4 
Cread una matriz de tres dimensiones de unos, igual a la matriz de tres dimensiones creada en el primer ejercicio.

In [8]:
matriz_2 = np.ones_like(array_3)
matriz_2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Ejercicio 5
Realizar operaciones

In [9]:
# 1) ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

#suma = array_2 + matriz_1
#print(array_2)
#print(matriz_1)

#No se pueden sumar, como hemos comprobado, porque tienen diferentes formas. Ambos son bidimensionales, pero el número de filas y columnas no es el mismo (2, 3) y (3, 3)



In [10]:
# 2) En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

#opción: crear array nuevo con las mismas dimensiones: como en este caso la matriz es de tamaño 3x3, nuestro array deberá tener 3 filas y 3 columnas.

array_nuevo = np.random.randint(1, 10, (3, 3))
print("Este es el array nuevo:", "\n", array_nuevo)

#Probamos a sumar array_nuevo con matriz_2

# a) Con operador

suma = array_nuevo + matriz_ident
print("El resultado de sumar con '+' es:", "\n",suma)

# b) Con método

suma_met = np.add(array_nuevo, matriz_ident)
print("El resultado de sumar con el método np.add es:", "\n", suma_met)
#Ahora tiene las mismas dimensiones y suma a array_nuevo (con random ints) los "unos y ceros" de matriz_1

Este es el array nuevo: 
 [[2 4 7]
 [7 3 4]
 [7 6 8]]
El resultado de sumar con '+' es: 
 [[3. 4. 7.]
 [7. 4. 4.]
 [7. 6. 9.]]
El resultado de sumar con el método np.add es: 
 [[3. 4. 7.]
 [7. 4. 4.]
 [7. 6. 9.]]


In [11]:
# 3) Multiplicación matriz_ident por array_nuevo
# a) Con operador
mult = matriz_ident * array_nuevo
print("El resultado de multiplicar con '*' es:", "\n",mult)

#b) Con método
mult_metodo = np.multiply(matriz_ident, array_nuevo)
print("El resultado de multiplicar con el método np.multiply es:", "\n",mult_metodo)


El resultado de multiplicar con '*' es: 
 [[2. 0. 0.]
 [0. 3. 0.]
 [0. 0. 8.]]
El resultado de multiplicar con el método np.multiply es: 
 [[2. 0. 0.]
 [0. 3. 0.]
 [0. 0. 8.]]


4. Dividid las dos matrices

In [12]:
# a) Con operador
div = matriz_ident / array_nuevo
print("El resultado de dividir con '/' es:", "\n", div)

#b) Con método
div_metodo = np.divide(matriz_ident, array_nuevo)
print("El resultado de dividir la matriz identidad con el método np.divide es:", "\n", div_metodo)

# c) Como quizá tenga más sentido dividir, al contrario, el array entre la matriz:

div_metodo2 = np.divide(array_nuevo, matriz_ident)
print("El resultado de dividir el array nuevo entre la matriz identidad con el método np.divide es:", "\n", div_metodo)

#Dividir entre ceros


El resultado de dividir con '/' es: 
 [[0.5        0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.125     ]]
El resultado de dividir la matriz identidad con el método np.divide es: 
 [[0.5        0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.125     ]]
El resultado de dividir el array nuevo entre la matriz identidad con el método np.divide es: 
 [[0.5        0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.125     ]]


/tmp/ipykernel_355/712860815.py:11: RuntimeWarning: divide by zero encountered in true_divide
  div_metodo2 = np.divide(array_nuevo, matriz_ident)
